#!/usr/bin/env bash

git init -qqq
git remote add origin https://github.com/Hawksama/docker-magento
git fetch origin -qqq
git checkout origin/master -- compose

# Ensure these are created so Docker doesn't create them as root
mkdir -p ~/.composer ~/.ssh

mv compose/* ./
rm -rf compose .git

# Check if "src" directory exists
if [ -d "src" ]; then
  # If "src" exists, rename it to "src-old"
  mv src src-old
fi

# Create a new "src" directory
mkdir src
